spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:vacinpb-test
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2