spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:vacinpb-test
    username: test
    password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always